name: Run Spyder Crawlers

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-crawlers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run static crawler (Douban)
        run: python static.py

      - name: Run API crawler (Weather)
        run: python app.py

      - name: Upload output files
        uses: actions/upload-artifact@v3
        with:
          name: crawler-results
          path: |
            static.json
            weather.csv
